# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPH' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SPH
  pod 'Alamofire', '~> 5.1.0'

  target 'SPHTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SPHUITests' do
    # Pods for testing
  end

end
